import {
  FiBookOpen,
  FiBookmark,
  FiCode,
  FiFileText,
  FiHeadphones,
  FiHome,
  FiMapPin,
  FiPaperclip,
  FiUser,
  FiZap,
} from 'react-icons/fi';

export const actions = [
  {
    id: 'home',
    name: 'Home',
    shortcut: ['h'],
    keywords: 'home',
    perform: () => (window.location.pathname = '/'),
    section: 'Navigation',
    icon: FiHome({ size: '1rem' }),
  },
  {
    id: 'about',
    name: 'About',
    shortcut: ['a'],
    keywords: 'about',
    perform: () => (window.location.pathname = '/about'),
    section: 'Navigation',
    icon: FiUser({ size: '1rem' }),
  },
  {
    id: 'resume',
    name: 'Resume',
    shortcut: ['r'],
    keywords: 'resume',
    perform: () => (window.location.pathname = '/resume'),
    section: 'Navigation',
    icon: FiFileText({ size: '1rem' }),
  },
  {
    id: 'places',
    name: 'Places',
    shortcut: ['p'],
    keywords: 'places locations map',
    perform: () => (window.location.pathname = '/places'),
    section: 'Navigation',
    icon: FiMapPin({ size: '1rem' }),
  },
  {
    id: 'links',
    name: 'Links',
    shortcut: ['l'],
    keywords: 'email link discord twitter github',
    perform: () => (window.location.pathname = '/links'),
    section: 'Navigation',
    icon: FiPaperclip({ size: '1rem' }),
  },
  {
    id: 'guestbook',
    name: 'Guestbook',
    shortcut: ['g'],
    keywords: 'guestbook',
    perform: () => (window.location.pathname = '/guestbook'),
    section: 'Navigation',
    icon: FiBookOpen({ size: '1rem' }),
  },
  {
    id: 'spotify',
    name: 'Spotify',
    shortcut: ['s'],
    keywords: 'spotify music stats',
    perform: () => (window.location.pathname = '/spotify'),
    section: 'Navigation',
    icon: FiHeadphones({ size: '1rem' }),
  },
  {
    id: 'dashboard',
    name: 'Dashboard',
    shortcut: ['d'],
    keywords: 'dashboard stars age stats',
    perform: () => (window.location.pathname = '/dashboard'),
    section: 'Navigation',
    icon: FiZap({ size: '1rem' }),
  },
  {
    id: 'blog',
    name: 'Blog',
    shortcut: ['b'],
    keywords: 'writing words article',
    perform: () => window.open('https://dev.to/womb0comb0', '_blank'),
    section: 'External',
    icon: FiBookmark({ size: '1rem' }),
  },
  {
    id: 'projects',
    name: 'Projects',
    shortcut: ['j'],
    keywords: 'projects',
    perform: () => window.open('https://github.com/WomB0ComB0', '_blank'),
    section: 'External',
    icon: FiCode({ size: '1rem' }),
  },
];
