github: WomB0ComB0
custom: ['https://opencollective.com/mike-odnis', 'https://buymeacoffee.com/mikeodnis3a', 'https://www.youtube.com/channel/UCMFxN_Gp1I_PU6hWzsqUqSw', 'https://www.twitch.tv/womb0_comb01']
