import {
  FiAward,
  FiBarChart,
  FiBookOpen,
  FiBriefcase,
  FiClipboard,
  FiFileText,
  FiHeadphones,
  FiHeart,
  FiHome,
  FiMapPin,
} from 'react-icons/fi';
import { SiHashnode } from 'react-icons/si';

export const actions = [
  {
    id: 'home',
    name: 'Home',
    shortcut: ['h'],
    keywords: 'home',
    perform: () => (window.location.pathname = '/'),
    section: 'Navigation',
    icon: FiHome({ size: '1rem' }),
  },
  {
    id: 'projects',
    name: 'Projects',
    shortcut: ['p'],
    keywords: 'projects portfolio work code',
    perform: () => (window.location.pathname = '/projects'),
    section: 'Navigation',
    icon: FiBriefcase({ size: '1rem' }),
  },
  {
    id: 'experience',
    name: 'Experience',
    shortcut: ['x'],
    keywords: 'experience work history jobs',
    perform: () => (window.location.pathname = '/experience'),
    section: 'Navigation',
    icon: FiClipboard({ size: '1rem' }),
  },
  {
    id: 'certifications',
    name: 'Certifications',
    shortcut: ['c'],
    keywords: 'certifications credentials certificates',
    perform: () => (window.location.pathname = '/certifications'),
    section: 'Navigation',
    icon: FiAward({ size: '1rem' }),
  },
  {
    id: 'resume',
    name: 'Resume',
    shortcut: ['r'],
    keywords: 'resume cv',
    perform: () => (window.location.pathname = '/resume'),
    section: 'Navigation',
    icon: FiFileText({ size: '1rem' }),
  },
  {
    id: 'blog',
    name: 'Blog',
    shortcut: ['b'],
    keywords: 'blog writing articles posts',
    perform: () => (window.location.pathname = '/blog'),
    section: 'Navigation',
    icon: SiHashnode({ size: '1rem' }),
  },
  {
    id: 'places',
    name: 'Places',
    shortcut: ['l'],
    keywords: 'places locations map travel',
    perform: () => (window.location.pathname = '/places'),
    section: 'Navigation',
    icon: FiMapPin({ size: '1rem' }),
  },
  {
    id: 'spotify',
    name: 'Spotify',
    shortcut: ['s'],
    keywords: 'spotify music stats listening',
    perform: () => (window.location.pathname = '/spotify'),
    section: 'Navigation',
    icon: FiHeadphones({ size: '1rem' }),
  },
  {
    id: 'guestbook',
    name: 'Guestbook',
    shortcut: ['g'],
    keywords: 'guestbook messages comments',
    perform: () => (window.location.pathname = '/guestbook'),
    section: 'Navigation',
    icon: FiBookOpen({ size: '1rem' }),
  },
  {
    id: 'stats',
    name: 'Stats',
    shortcut: ['d'],
    keywords: 'stats analytics',
    perform: () => (window.location.pathname = '/stats'),
    section: 'Navigation',
    icon: FiBarChart({ size: '1rem' }),
  },
  {
    id: 'sponsor',
    name: 'Sponsor',
    shortcut: ['$'],
    keywords: 'sponsor support donate contribute funding',
    perform: () => (window.location.pathname = '/sponsor'),
    section: 'Navigation',
    icon: FiHeart({ size: '1rem' }),
  },
];
