name: Snyk Auto Merge

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'snyk-bot' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Approve and enable auto-merge for Snyk PRs
        uses: CondeNast/snyk-pr-action@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          approve: true
          merge: true
          merge-minor: true
          merge-patch: true
