name: ⚡ Testing

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  cancel-in-progress: true
  group: testing-${{ github.ref }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
      NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID }}
      NEXT_PUBLIC_DISCORD_ID: ${{ secrets.NEXT_PUBLIC_DISCORD_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WAKA_TIME_API_KEY: ${{ secrets.WAKA_TIME_API_KEY }}
      SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
      SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      NEXT_PUBLIC_HASHNODE_TOKEN: ${{ secrets.NEXT_PUBLIC_HASHNODE_TOKEN }}
      REACT_EDITOR: ${{ secrets.REACT_EDITOR }}
      NEXT_PUBLIC_STRIPE_SECRET_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_SECRET_KEY }}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
      NEXT_PUBLIC_STRIPE_WEBHOOK_SECRET: ${{ secrets.NEXT_PUBLIC_STRIPE_WEBHOOK_SECRET }}
      NEXT_PUBLIC_GCP_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_GCP_PROJECT_ID }}
      NEXT_PUBLIC_GCP_PRIVATE_KEY_ID: ${{ secrets.NEXT_PUBLIC_GCP_PRIVATE_KEY_ID }}
      NEXT_PUBLIC_GCP_PRIVATE_KEY: ${{ secrets.NEXT_PUBLIC_GCP_PRIVATE_KEY }}
      NEXT_PUBLIC_GCP_CLIENT_EMAIL: ${{ secrets.NEXT_PUBLIC_GCP_CLIENT_EMAIL }}
      NEXT_PUBLIC_GCP_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GCP_CLIENT_ID }}
      NEXT_PUBLIC_GCP_CLIENT_X509_CERT_URL: ${{ secrets.NEXT_PUBLIC_GCP_CLIENT_X509_CERT_URL }}
      NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY: ${{ secrets.NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install
      - name: Build code
        env:
          NODE_ENV: production  # Set to a standard value
          SKIP_BUILD_PRODUCT_REDIRECTS: 1
        run: bun run build
      - name: Test code
        run: bun run test
